Repository PgBiel/typst-tablex, pull requests merged in 2023-12, with the labels that each got.

#84 utilities: fix issues related to conversion of lengths to pt
  src/col-row-size.typ
  src/option-parsing.typ
  src/type-validators.typ
  src/utilities.typ
  tablex-test.typ
Labels: bug

#90 Merge 0.0.7 changes
  tablex-test.pdf
  tablex-test.typ
  tablex.typ
Labels: bug, enhancement, meta

#93 Release 0.0.7
  README.md
  typst.toml
Labels: packaging, meta

#100 `calc.mod` -> `calc.rem`
  README.md
Labels: documentation

#106 Use fields from Typst 0.7.0 when possible
  src/common.typ
  src/type-validators.typ
  src/utilities.typ
Labels: enhancement

#107 Fix height of rows with no drawn cells being ignored
  src/common.typ
  src/renderer/old.typ
  tablex-test.typ
Labels: bug, renderer

#108 Fix extra rows always having `auto` height
  src/tablex.typ
  tablex-test.typ
Labels: bug, table-parity
